### ISSUE TITLE
DB検討

### ISSUE THREAD

**Issue by kyokucho1989** [kyokucho1989/lytcycle#5]
Method | Path | Description
-- | -- | --
GET | / | ランディングページ
GET |/users/sign_in(.:format) | ログインページ|
POST|/users/sign_in(.:format) | ログイン|
DELETE |/users/sign_out(.:format) | ログアウト|
GET | /simulations | トップページ(シミュレーション一覧ページ)
GET | /simulations/new | シミュレーション新規作成フォームの表示
POST | /simulations | シミュレーション新規作成
GET | /simulations/:simulation_id/edit | シミュレーション編集ページ
GET | /simulations/:simulation_id | シミュレーション詳細ページ(編集モード/実行モード)
PUT | /simulations/:simulation_id | シミュレーション保存
DELETE | /simulations/:simulation_id  | シミュレーション削除
GET | / users/edit(.:format) | アカウント編集フォーム
PUT| / users/edit(.:format)| アカウント編集
DELETE| /users(.:format)  | アカウント削除
GET | /guides | シミュレーション 操作説明
GET | /terms| プライバシーポリシー

- シミュレーションは詳細画面でページ遷移なしに編集モードと実行モードを切り替え
- シミュレーション編集ページでは、そのシミュレーションの名前を変えるのみ可能
- シミュレーション詳細画面で細かいパラメータを編集し、編集ページに遷移する際にそのパラメータを渡す

- ログイン関係のリソースはdeviseのgemに準拠
- 操作説明と、プライバシーポリシーのページは単一ページ

# データベース設計

## Users
|カラム名| 型| 備考|
-- | -- | --
|id| integer | - |
|email| string |- |
|name| string |- |
|encrypted_password| string |- |
|reset_password_token| string| - |
|reset_password_sent_at| datetime| - |
|remember_created_at| datetime| - |
|sign_in_count| integer| - |
|current_sign_in_at| datetime| - |
|last_sign_in_at| datetime| - |
|current_sign_in_ip| string| - |
|last_sign_in_ip| string - |

- has many :simulation

## Simulations
|カラム名| 型| 備考|
-- | -- | --
|id| integer|- |
|user_id| integer | - |
|routes| jsonb |  - | 
|operators| jsonb | -|
|facilities| jsonb | -|

- belongs_to :user

jsonb について
https://www.postgresql.jp/docs/11/datatype-json.html
https://guides.rubyonrails.org/active_record_postgresql.html

### routes
```js
{routes : [
  { id: 1, source: 1, target: 2, distance: 20, name: "root10" },
  { id: 2, source: 2, target: 3, distance: 25, name: "root11" },
  { id: 3, source: 2, target: 1, distance: 15, name: "re_root10" },
  { id: 4, source: 3, target: 2, distance: 30, name: "re_root11" }
]
}
```
- facilities間をつなぐ道
- 行きと帰りの道がそれぞれ存在する

### operators
```js
{operators : [
  { id: 1, name: "Alice", target_routes: [(ルートのidの配列)] },
  { id: 2, name: "Bob", target_routes: [(ルートのidの配列)] },]
}
```

オペレータごとに通るルートを設定できる
（この設備間の搬送はこのオペレーターが担う、という設定ができる）

### facilities
```js
{facilities : [
  { id: 1, x: 0, y: 60, processingTime: 1, type: "start", name: "start-point" },
  { id: 2, x: 330, y: 130, processingTime: 15, type: "machine", name: "machine-no-1" },
  { id: 3, x: 530, y: 60, processingTime: 1, type: "goal", name: "goal-point" },
]
}
```

- キャンパスに配置する座標を保存
- 加工時間を設定

**Comment by maedana** [comment]
### リソース設計について

> GET	/simulation	トップページ(シミュレーション一覧ページ)

複数あるものですよね? 複数形にしましょうー。他のルーティングも同様です

### データベース設計について

> Users

- Railsのdevise前提ですか? だとしたら色々カラム足りないと思いますが、省略しているのでしょうか? それとも何か違う想定でしょうか。
- PrimaryKeyは外部キーと区別がつくように単に`id`としておくほうがいいのではないでしょうか? Rails標準だとこうなってますね。

> Simulations

- PrimaryKeyについて同上です。
- string型にjsonを入れる箇所がありますが、Postgres前提だとするならjsonやjsonbのほうがいい気がしました。どんなものかは調べてみてください。
- routes/operators/facilitiesをそれぞれテーブルに分割するほうが固いデータ構造になりそうですが、jsonをそのまま入れる設計にしたのはなにか理由があるんでしょうか。

**Comment by kyokucho1989** [comment]
@maedana 
ありがとうございます！　修正しました。

 > GET /simulation トップページ(シミュレーション一覧ページ)
> 複数あるものですよね? 複数形にしましょうー。他のルーティングも同様です

　修正しました！


> データベース設計について
> Users
> Railsのdevise前提ですか? だとしたら色々カラム足りないと思いますが、省略しているのでしょうか? それとも何か違う想定でしょうか。

　すみません。省略していただけです... 。　デフォルトで設定されるカラムを追記しました。

> PrimaryKeyは外部キーと区別がつくように単にidとしておくほうがいいのではないでしょうか? Rails標準だとこうなってますね。
> Simulations
> PrimaryKeyについて同上です。

　修正しました！


> string型にjsonを入れる箇所がありますが、Postgres前提だとするならjsonやjsonbのほうがいい気がしました。どんなものかは調べてみてください。

　調べました！stringに変換しないと使えないと勝手に思っていました。json型があるのですね... 。jsonbの方が処理速度に優れており、今回のアプリではオブジェクトキーの順序に配慮するなどの制約はないため、jsonbを採用しようと思います。

> routes/operators/facilitiesをそれぞれテーブルに分割するほうが固いデータ構造になりそうですが、jsonをそのまま入れる設計にしたのはなにか理由があるんでしょうか。

　「routes/operators/facilities」は他のsimulationモデルに使い回さず、ひとつのsimulation データ固有のものです。そのためテーブルをつくらずに、カラムを使おうと考えました。

**Comment by maedana** [comment]
> 　「routes/operators/facilities」は他のsimulationモデルに使い回さず、ひとつのsimulation データ固有のものです。そのためテーブルをつくらずに、カラムを使おうと考えました。

OKです。ただ、こういう設計ですと例えば
- 細かいvalidationをmodel側でかけたりしにくそう
- もし後から `routes/operators/facilities`に属性を追加/削除/更新などかけたくなったときのデータ移行が大変そう(データ構造変更による後方互換性維持など苦労するかも...?)

などのデメリットもありそうな気がします。とはいえ、おそらくあまり厳密性が求められるものでもないのだと判断しますので、一旦これで進めてみましょうか。

**Comment by kyokucho1989** [comment]
@maedana 
ありがとうございます。
一旦この設計で進めていきたいと思います！
